CREATE DATABASE crowdfunding_db;
USE crowdfunding_db;

CREATE TABLE CATEGORY (
    CATEGORY_ID INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL
);

CREATE TABLE FUNDRAISER (
    FUNDRAISER_ID INT AUTO_INCREMENT PRIMARY KEY,
    ORGANIZER VARCHAR(100) NOT NULL,
    CAPTION TEXT NOT NULL,
    TARGET_FUNDING DECIMAL(10, 2) NOT NULL,
    CURRENT_FUNDING DECIMAL(10, 2) DEFAULT 0.00,
    CITY VARCHAR(100) NOT NULL,
    ACTIVE BOOLEAN DEFAULT TRUE,
    CATEGORY_ID INT,
    FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORY(CATEGORY_ID)
);
INSERT INTO CATEGORY (NAME) VALUES ('Education'), ('Healthcare'), ('Community Support');

INSERT INTO FUNDRAISER (ORGANIZER, CAPTION, TARGET_FUNDING, CURRENT_FUNDING, CITY, ACTIVE, CATEGORY_ID) 
VALUES 
('John Doe', 'Help build a school', 5000.00, 1500.00, 'New York', TRUE, 1),
('Jane Smith', 'Support cancer treatment', 10000.00, 8000.00, 'Los Angeles', TRUE, 2),
('Community Aid', 'Food for homeless', 7500.00, 3500.00, 'Chicago', TRUE, 3);

